-- Migration 013: Ajout d'un lot d'agences interdites
INSERT INTO forbidden_agencies (name, normalized_name) VALUES
  ('Tawaf Voyages', 'tawaf voyages'),
  ('Alsirate Voyage', 'alsirate voyage'),
  ('Partir à la Mecque', 'partir a la mecque'),
  ('Autre Voyage', 'autre voyage'),
  ('Labbayk Voyages', 'labbayk voyages'),
  ('Oran Voyages', 'oran voyages'),
  ('Marwa Voyages', 'marwa voyages'),
  ('Safar Muslim', 'safar muslim'),
  ('Safa Voyages', 'safa voyages'),
  ('Yati Voyages', 'yati voyages'),
  ('Go-Makkah', 'go makkah'),
  ('Omra Pour Tous', 'omra pour tous'),
  ('my omra', 'my omra'),
  ('Omra Excellence Paris', 'omra excellence paris'),
  ('Salam Tours', 'salam tours'),
  ('Djemila Voyages', 'djemila voyages'),
  ('Go Qibla', 'go qibla'),
  ('Soprom Lyon Voyages', 'soprom lyon voyages'),
  ('Neostream Voyages', 'neostream voyages'),
  ('Marhaba Travel', 'marhaba travel'),
  ('Al Baraqa Voyages', 'al baraqa voyages'),
  ('Zamzam Voyages', 'zamzam voyages'),
  ('Omra France Sud', 'omra france sud'),
  ('Hérault Voyages', 'herault voyages'),
  ('Omra Voyage', 'omra voyage'),
  ('Asfar Voyages', 'asfar voyages'),
  ('Al Bouraq Travel', 'al bouraq travel'),
  ('Hajir Tours', 'hajir tours'),
  ('Pelerinhajj', 'pelerinhajj'),
  ('Furqan Voyage', 'furqan voyage'),
  ('Arafat Voyages', 'arafat voyages'),
  ('Go Omra', 'go omra'),
  ('Al Maqam Voyages', 'al maqam voyages'),
  ('Atout France', 'atout france'),
  ('Omra Discount', 'omra discount'),
  ('Haramain Voyages', 'haramain voyages'),
  ('Al Amana Travel', 'al amana travel'),
  ('Al Waseet Travel', 'al waseet travel'),
  ('Go2Omra', 'go2omra'),
  ('Tayba Travel', 'tayba travel'),
  ('Medina Travel', 'medina travel'),
  ('Minhaj Voyages', 'minhaj voyages'),
  ('AB Tours', 'ab tours'),
  ('Tawhid Voyages', 'tawhid voyages'),
  ('Dogan Voyages Belgium', 'dogan voyages belgium'),
  ('Liberta Voyages', 'liberta voyages'),
  ('Battuta Travel', 'battuta travel'),
  ('Destination Mekkah', 'destination mekkah'),
  ('DM Travel', 'dm travel'),
  ('Al Qods Voyages', 'al qods voyages'),
  ('Al Aqsa Travel', 'al aqsa travel'),
  ('Al Madina Travel', 'al madina travel'),
  ('Makkah Travel', 'makkah travel'),
  ('Al Baraka Voyages', 'al baraka voyages'),
  ('Rahma Voyages', 'rahma voyages'),
  ('Dar El Salam Travel', 'dar el salam travel'),
  ('Atlas Travel', 'atlas travel'),
  ('Tibouda Travel', 'tibouda travel'),
  ('Al Fadl', 'al fadl'),
  ('Al Fadl Genève et Le Locle', 'al fadl geneve et le locle'),
  ('Jinene Travel', 'jinene travel'),
  ('Jinene Travel départs de Genève', 'jinene travel departs de geneve'),
  ('Alatik Travel', 'alatik travel'),
  ('Alatik Travel & Services', 'alatik travel services'),
  ('Alatik Travel & Services Genève', 'alatik travel services geneve'),
  ('Safira Travel', 'safira travel'),
  ('Swiss Omra', 'swiss omra'),
  ('Agence Swiss Omra', 'agence swiss omra'),
  ('Bon Hajj', 'bon hajj'),
  ('Bon Hajj & Omra', 'bon hajj omra'),
  ('Al Madina Voyages', 'al madina voyages'),
  ('Al Haramain Travel', 'al haramain travel'),
  ('Al Manar Voyages', 'al manar voyages'),
  ('Swiss Muslim Travel', 'swiss muslim travel'),
  ('Nour Voyages', 'nour voyages'),
  ('Bakkah', 'bakkah'),
  ('Medin Voyages', 'medin voyages'),
  ('NEXSAFAR', 'nexsafar'),
  ('Good Safar', 'good safar'),
  ('Aswar Voyages', 'aswar voyages'),
  ('Swiss Umrah', 'swiss umrah'),
  ('Nur Travel', 'nur travel'),
  ('SkyTravels', 'skytravels'),
  ('Hajj Travel & Manasik', 'hajj travel manasik'),
  ('Swiss Riva', 'swiss riva')
ON CONFLICT (normalized_name) DO UPDATE SET name = EXCLUDED.name;
